version: "3.8"
networks:
  jenkins:
volumes:
  jenkins-data:
  jenkins-docker-certs:
services:
  jenkins:
    image: jenkins-sandbox
    build:
      dockerfile: Dockerfile
    container_name: jenkins-sandbox
    networks:
     - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro